In [2]:
import numpy as np
from src.policy.multiple_play.contextfree import MultiplePlayRandomPolicy

In [3]:
policy = MultiplePlayRandomPolicy(10, 3)

In [4]:
a = np.arange(10)

In [141]:
cnt = np.random.randint(0, 10, size=(10, 3)) + 1
reward = np.random.binomial(1, 0.5, size=(10, 3))

In [144]:
n_kl = cnt[0]
s_kl = reward[0]
kappa = np.array([1, 0.5, 0.1])
delta = 0.1

f(q, kappa, n_kl, s_kl)

0.6978389146803373

In [155]:
from scipy import optimize as opt

def compute_U(kappa, n_kl, s_kl, delta):
    def kl(p, q, eps=1e-7):
        return p * np.log(p / q + eps) + (1 - p) * np.log((1 - p) / (1 - q) + eps)

    def f(q, kappa, n_kl, s_kl):
        theta = s_kl / n_kl
        d = kl(theta, kappa * q)
        return (theta * d).sum()

    min_theta = opt.minimize_scalar(f, args=(kappa, n_kl, s_kl), bounds=(0, 1), method="bounded").x
    cons = {
        "type": "ineq",
        "fun": lambda q: delta - f(q, kappa, n_kl, s_kl),
    }
    x0 = np.array(min_theta)
    bounds = [(min_theta, 1)]
    return opt.minimize(lambda q: -q, x0=x0, constraints=cons, method="SLSQP", bounds=bounds).x

In [169]:
[
    compute_U(kappa, n_kl, s_kl, delta) for n_kl, s_kl in zip(cnt, reward)
]

[array([1.]),
 array([0.472315]),
 array([0.78708876]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([0.75937932]),
 array([1.]),
 array([1.]),
 array([1.])]